### ISSUE TITLE
revert ids to text

### ISSUE THREAD

**Issue by SourceForge-exporter** [MICommunity/psidev#17]
id attributes for interactions and experiments are
currently of type xs:ID. 
This means they may only occur exactly once per file.
This defeats two aspects of the MIF format:
- The denormalised form would list the interactors and
therefore their ids potentially several times in an
experiment.

\- The idea of the two-level "entry-entryset" is to have
entries as the independent unit, and allow easy
concatenation of entry elements from many files into a
single one. Even in the normalised form this is
currently not possible if different entries contain the
same interactors.

The solution of adding arbitrary numbers to the ids is
a very unelegant solution.

Reverting the type if IDs to text would solve the
problem, be backwards-compatible loose only a minimal
consistency check.

Reported by: hhe

**Comment by linuxlovell** [comment]
thanks www.movied.org
