### ISSUE TITLE
MIF25_view.xsl: Incorrect colon placement

### ISSUE THREAD

**Issue by SourceForge-exporter** [MICommunity/psidev#3]
Generating the HTML "Name:" line from shortLabel and
fullName: The blank (using underscore in the example)
should be after the colon, not before:

rhp9-rad4_:Yeast 2 hybrid analysis reveals interaction
between the Rhp9 protein and Rad4 protein

should be

rhp9-rad4:_Yeast 2 hybrid analysis reveals interaction
between the Rhp9 protein and Rad4 protein 

(submitted on behalf of Henning)

Reported by: aquinn

**Comment by linuxjackto1** [comment]
thanks www.movied.org
