### ISSUE TITLE
addition of attribute 'uncertainty' to parameter

### ISSUE THREAD

**Issue by SourceForge-exporter** [MICommunity/psidev#46]
To store errors associated to a parameter, it would be
helpful to have a dedicated attribute. 

Note 1: the error value should have the same exponent
and unit that the parameter value
Note 2: by default the parameter value is affected by
'+-' the uncertainty value.

example Ki = 1.3e-9 ± 0.5e-9  :

term parameterType, example ki,
unit parameterUnit, example molar
base 10
exponent -9
factor 1.3
UNCERTAINTY 0.5

Reported by: luisa_montecchi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
