### ISSUE TITLE
MIF_view: Show host organism for Experiment and Participant

### ISSUE THREAD

**Issue by SourceForge-exporter** [MICommunity/psidev#52]
Subject: IMEx Test Curation sets
Date: Tue, 04 Apr 2006 09:36:36 +0100
From: Sandra Orchard
To: Antony Quinn

Hi Antony

I believe you did the conversion of the IMEx XML files
into expanded/compact form and then to HTML for
Henning. I'm working from the HTML form to compare
annotation practices and have noticed there is a 
section of information missing from each entry, namely
the host organism on both Experiment and Participant.
It is in the XML form and on the compact version, I
can't open the expanded form so cannot comment on that.

Any chance of adding it to the HTML view which is much
easier to read.

Sandra

Example from 
http://www.ebi.ac.uk/~hhe/tmp/testCuration/tmp/intact\_10567532-compact.xml

Host organism on experiment

&lt;experimentList&gt;
-
&lt;experimentDescription id="14"&gt;
-
&lt;names&gt;
&lt;shortLabel&gt;chang-1999a-3&lt;/shortLabel&gt;
-
&lt;fullName&gt;
Direct binding and In vivo regulation of the fission
yeast p21-activated 
kinase shk1 by the SH3 domain protein scd2.
&lt;/fullName&gt;
&lt;/names&gt;
-
&lt;bibref&gt;
-
&lt;xref&gt;
&lt;primaryRef db="pubmed" dbAc="MI:0446" id="10567532" 
refType="primary-reference" refTypeAc="MI:0358"/&gt;
&lt;/xref&gt;
&lt;/bibref&gt;
-
&lt;xref&gt;
&lt;primaryRef db="intact" dbAc="MI:0469" id="EBI-767472" 
secondary="chang-1999a-3"/&gt;
&lt;secondaryRef db="newt" dbAc="MI:0247" id="4896" 
refType="target-species" secondary="schpo"/&gt;
&lt;/xref&gt;
-
&lt;hostOrganismList&gt;
-
&lt;hostOrganism ncbiTaxId="-1"&gt;
-
&lt;names&gt;
&lt;shortLabel&gt;in vitro&lt;/shortLabel&gt;
&lt;/names&gt;
&lt;/hostOrganism&gt;
&lt;/hostOrganismList&gt;
-
&lt;interactionDetectionMethod&gt;

Host organism on Participant

&lt;/interaction&gt;
-
&lt;interaction id="13"&gt;
-
&lt;names&gt;
&lt;shortLabel&gt;shk1-scd2&lt;/shortLabel&gt;
-
&lt;fullName&gt;
Protein kinase assay demonstrates Shk1 phosphorylates
Scd2 in vitro
&lt;/fullName&gt;
&lt;/names&gt;
-
&lt;xref&gt;
&lt;primaryRef db="intact" dbAc="MI:0469" id="EBI-767474" 
secondary="shk1-scd2"/&gt;
&lt;/xref&gt;
-
&lt;experimentList&gt;
&lt;experimentRef&gt;14&lt;/experimentRef&gt;
&lt;/experimentList&gt;
-
&lt;participantList&gt;
-
&lt;participant id="15"&gt;
&lt;interactorRef&gt;7&lt;/interactorRef&gt;
-
&lt;biologicalRole&gt;
-
&lt;names&gt;
&lt;shortLabel&gt;enzyme&lt;/shortLabel&gt;
&lt;fullName&gt;enzyme&lt;/fullName&gt;
&lt;/names&gt;
-
&lt;xref&gt;
&lt;primaryRef db="psi-mi" dbAc="MI:0488" id="MI:0501"
refType="identity" 
refTypeAc="MI:0356"/&gt;
&lt;secondaryRef db="pubmed" dbAc="MI:0446" id="14755292" 
refType="primary-reference" refTypeAc="MI:0358"/&gt;
&lt;/xref&gt;
&lt;/biologicalRole&gt;
-
&lt;experimentalRoleList&gt;
-
&lt;experimentalRole&gt;
-
&lt;names&gt;
&lt;shortLabel&gt;neutral component&lt;/shortLabel&gt;
&lt;fullName&gt;neutral component&lt;/fullName&gt;
&lt;/names&gt;
-
&lt;xref&gt;
&lt;primaryRef db="psi-mi" dbAc="MI:0488" id="MI:0497"
refType="identity" 
refTypeAc="MI:0356"/&gt;
&lt;secondaryRef db="pubmed" dbAc="MI:0446" id="14755292" 
refType="primary-reference" refTypeAc="MI:0358"/&gt;
&lt;/xref&gt;
&lt;/experimentalRole&gt;
&lt;/experimentalRoleList&gt;
-
&lt;featureList&gt;
-
&lt;feature id="16"&gt;
-
&lt;names&gt;
&lt;shortLabel&gt;6his-tag&lt;/shortLabel&gt;
&lt;/names&gt;
-
&lt;featureType&gt;
-
&lt;names&gt;
&lt;shortLabel&gt;his tagged&lt;/shortLabel&gt;
&lt;fullName&gt;his tagged&lt;/fullName&gt;
&lt;alias&gt;6-His-tagged&lt;/alias&gt;
&lt;alias&gt;Hexa-His-tagged&lt;/alias&gt;
&lt;alias&gt;Histidine-tagged&lt;/alias&gt;
&lt;/names&gt;
-
&lt;xref&gt;
&lt;primaryRef db="psi-mi" dbAc="MI:0488" id="MI:0521"
refType="identity" 
refTypeAc="MI:0356"/&gt;
&lt;secondaryRef db="pubmed" dbAc="MI:0446" id="14755292" 
refType="go-definition-ref" refTypeAc="MI:0242"/&gt;
&lt;/xref&gt;
&lt;/featureType&gt;
-
&lt;featureRangeList&gt;
-
&lt;featureRange&gt;
-
&lt;startStatus&gt;
-
&lt;names&gt;
&lt;shortLabel&gt;undetermined&lt;/shortLabel&gt;
&lt;fullName&gt;undetermined sequence position&lt;/fullName&gt;
&lt;/names&gt;
-
&lt;xref&gt;
&lt;primaryRef db="psi-mi" dbAc="MI:0488" id="MI:0339"
refType="identity" 
refTypeAc="MI:0356"/&gt;
&lt;secondaryRef db="pubmed" dbAc="MI:0446" id="14755292" 
refType="primary-reference" refTypeAc="MI:0358"/&gt;
&lt;/xref&gt;
&lt;/startStatus&gt;
&lt;begin position="0"/&gt;
-
&lt;endStatus&gt;
-
&lt;names&gt;
&lt;shortLabel&gt;undetermined&lt;/shortLabel&gt;
&lt;fullName&gt;undetermined sequence position&lt;/fullName&gt;
&lt;/names&gt;
-
&lt;xref&gt;
&lt;primaryRef db="psi-mi" dbAc="MI:0488" id="MI:0339"
refType="identity" 
refTypeAc="MI:0356"/&gt;
&lt;secondaryRef db="pubmed" dbAc="MI:0446" id="14755292" 
refType="primary-reference" refTypeAc="MI:0358"/&gt;
&lt;/xref&gt;
&lt;/endStatus&gt;
&lt;end position="0"/&gt;
&lt;/featureRange&gt;
&lt;/featureRangeList&gt;
&lt;/feature&gt;
&lt;/featureList&gt;
-
&lt;hostOrganismList&gt;
-
&lt;hostOrganism ncbiTaxId="4896"&gt;
-
&lt;names&gt;
&lt;shortLabel&gt;schpo&lt;/shortLabel&gt;
&lt;fullName&gt;Schizosaccharomyces pombe&lt;/fullName&gt;
&lt;/names&gt;
&lt;/hostOrganism&gt;
&lt;/hostOrganismList&gt;
&lt;/participant&gt;

Reported by: aquinn

**Comment by linuxjackto1** [comment]
thanks www.movied.org
