### ISSUE TITLE
psi-ms.obo

### ISSUE THREAD

**Issue by germa** [MICommunity/psidev#603]
The actual version of psi-ms.obo is located at
https://github.com/HUPO-PSI/psi-ms-CV

**Comment by colin-combe** [comment]
I think OBOFoundry needs to be updated then.

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/ms.md

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
